### ISSUE TITLE
Automated tests fail 

### ISSUE THREAD

**Issue by nsapoval** [treangenlab/lemur#11]
After the latest push the automated tests fail. No major changes were made to the code (minor error handling added). It appears that the problem has to do with how GitHub actions handle `conda` environments now. I'd appreciate if we can look into this and fix it.

**Comment by bkille** [comment]
It looks like there was a missing quotation in the code, but regardless, the CI is failing because of [this](https://github.com/conda-incubator/setup-miniconda/issues/344) new update 🙃

**Comment by nsapoval** [comment]
Merged into `main`, should I close the issue now?
